<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.tws.mes</groupId>
        <artifactId>mes-tws</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>mes-base</artifactId>
    <name>mes-base</name>
    <description>基础数据层：用户/登录、物料、批次、BOM、工序、工艺路线、产线工位、不良代码</description>

    <dependencies>
        <dependency>
            <groupId>com.tws.mes</groupId>
            <artifactId>mes-common</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>
